version: '3'

services:
   mongodb:
     image: mongo
     ports: 
       - 27017:27017
     container_name: "mongo_db"
     network_mode: host
     environment:
          MONGO_INITDB_DATABASE: movie-service

   spring:
     image: movie-service
     build: movie-service/.
     restart: always
     network_mode: host     
     container_name: "spring-app"
     depends_on: 
       - mongodb
     ports:
       - 8080:8080
     expose:
       - 8080

